### ISSUE TITLE
got error when github workflows build

### ISSUE THREAD

**Issue by umjammer** [umjammer/vavi-nio-file-googleplaymusic#1]
* 🚫 error

[github workflows](https://github.com/umjammer/vavi-nio-file-googleplaymusic/runs/648481217?check_suite_focus=true) env

```
Linux fv-az86 5.0.0-1035-azure #37-Ubuntu SMP Wed Mar 18 11:21:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (Zulu 8.46.0.19-CA-linux64) (build 1.8.0_252-b14)
OpenJDK 64-Bit Server VM (Zulu 8.46.0.19-CA-linux64) (build 25.252-b14, mixed mode)
```

```java
java.lang.AssertionError
	at okhttp3.internal.platform.Jdk9Platform.getSelectedProtocol(Jdk9Platform.java:69)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:285)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:237)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:148)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
	at okhttp3.RealCall.execute(RealCall.java:63)
	at svarzee.gps.gpsoauth.Gpsoauth.performMasterLogin(Gpsoauth.java:179)
	at svarzee.gps.gpsoauth.Gpsoauth.performMasterLoginForToken(Gpsoauth.java:196)
	at svarzee.gps.gpsoauth.Gpsoauth.performMasterLoginForToken(Gpsoauth.java:183)
	at svarzee.gps.gpsoauth.Gpsoauth.login(Gpsoauth.java:131)
	at com.github.felixgail.gplaymusic.util.TokenProvider.provideToken(TokenProvider.java:30)
	at vavi.net.auth.oauth2.googleplaymusic.GPMLocalAuthenticator.authorize(GPMLocalAuthenticator.java:43)
```

* ✅ no error

my env

```shell
$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/nsano/.sdkman/candidates/maven/current
Java version: 1.8.0_231, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/jre
Default locale: ja_JP, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"

$ java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

$ java -version                                   
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```

**Comment by umjammer** [comment]
https://github.com/svarzee/gpsoauth-java/issues/16

**Comment by umjammer** [comment]
https://www.infoq.com/news/2020/04/tls-alpn-java8/
